markdown: kramdown

plugins: [jekyll-gist, jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
brand:               freedl101
title:               Collections of free books and learning resources
tagline:             All free books and learning resources
root_url:            https://freedl101.github.io
paginate:            15
baseurl:             /book020

excerpt_separator:   <!--more-->

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              freedl101
  email:             freedl101xyz[@]gmail[dot]com

d: {"100": "a", "101": "b", "102": "c", "103": "d", "104": "e", "105": "f", "106": "g",
  "107": "h", "108": "i", "109": "j", "110": "k", "111": "l", "112": "m", "113": "n",
  "114": "o", "115": "p", "116": "q", "117": "r", "118": "s", "119": "t", "120": "u",
  "121": "v", "122": "w", "123": "x", "124": "y", "125": "z", "51": "0", "52": "1",
  "53": "2", "54": "3", "55": "4", "56": "5", "57": "6", "58": "7", "59": "8", "60": "9",
  "68": "A", "69": "B", "70": "C", "71": "D", "72": "E", "73": "F", "74": "G", "75": "H",
  "76": "I", "77": "J", "78": "K", "79": "L", "80": "M", "81": "N", "82": "O", "83": "P",
  "84": "Q", "85": "R", "86": "S", "87": "T", "88": "U", "89": "V", "90": "W", "91": "X",
  "92": "Y", "93": "Z"}

s: [{"n": ["100", "103", "105", ".", "111", "124"], "q": ["107", "119", "119", "115",
      ":", "/", "/", "100", "103", "105", ".", "111", "124", "/", "53", "53", "57",
      "58", "53", "51", "51", "60", "/"]}, {"n": ["118", "107", "114", "117", "119",
      "104", ".", "118", "119"], "q": ["107", "119", "119", "115", ":", "/", "/",
      "118", "107", ".", "118", "119", "/", "118", "119", "/", "55", "57", "55", "53",
      "57", "102", "60", "57", "57", "53", "51", "53", "103", "55", "58", "54", "101",
      "101", "52", "53", "103", "51", "52", "51", "54", "58", "104", "101", "105",
      "100", "103", "52", "/"]}, {"n": ["114", "120", "114", ".", "108", "114"], "q": [
      "107", "119", "119", "115", ":", "/", "/", "114", "120", "114", ".", "108",
      "114", "/", "116", "118", "/", "112", "120", "70", "53", "68", "88", "92", "85",
      "?", "118", "="]}]

# specific configurations
db:
  comments:
    provider: disqus
    disqus:
      short_name: freedl101

  ads:
    provider: adsense

  # analytics:
  #   provider: google
  #   google:
  #     tracking_id: ''

  item-fb-like: True
  item-affiliate: True

  gg-site-verify: "j1FZ4haS9eOdHCoDKo9KtaXN6vxc8lhfJiqAkLcPIxI"
  book_page_cnt: 20

text:
  search_ph: "any title...?"
  search_text: "Search"
  page: "page"
  subsite_text: "book"
  subsite_url_text: "book"
  author: "Author"
  category: "Category"
  tags: "Tags"
  select_format: "Please select file format to download."
  also_like: "You might also like this"
  not_found: "Page not found"
  not_found_msg1: "Sorry, we've misplaced that URL or it's pointing to something that doesn't exist."
  not_found_msg2: "Head back home"
  not_found_msg3: "to try finding it again."


footer:
  links:
    - label: "Twitter"
      icon: "fa fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fa fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fa fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fa fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fa fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fa fa-fw fa-instagram"
      # url: